grafana:
  enabled: false


prometheus:
  
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - "prometheus.fstack.store"
    paths:
      - /prometheus
    pathType: Prefix
