adminPassword: admin123

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - "grafana.fstack.store"
  path: /grafana
  pathType: Prefix
